### ISSUE TITLE
question on hw4

### ISSUE THREAD

**Issue by yudl21132** [uwhpsc-2016/homework4#11]
Hi, I posted my private question on hw4 issue page, and @ TAs, but no one answers me. I did that before for hw3 also, but it doesn't work. Could you please check it for me. Thanks.

**Comment by quantheory** [comment]
Your HW3 question was really about the quiz, which is why I didn't answer there. The TAs aren't involved in the quiz grading, so GitHub is probably the wrong place to ask about that. I probably should have said something at the time, but I didn't know if the instructor was looking at individual repos here.

I was in the middle of answering your HW4 question when you posted this; it's not that you put that question in the wrong place, it's just that you only posted it this morning, and it's a holiday, so you shouldn't really have expected an answer before tomorrow...
